CREATE TABLE BANCO (
    id_banco NUMBER (4) NOT NULL,
    nombre VARCHAR2 (25) NOT NULL
);

ALTER TABLE
    BANCO
ADD
    CONSTRAINT BANCO_PK PRIMARY KEY (id_banco);

CREATE TABLE CIUDAD (
    id_ciudad VARCHAR2 (40) NOT NULL,
    nombre_ciudad VARCHAR2 (50) NOT NULL,
    REGION_id_region VARCHAR2 (40) NOT NULL
);

ALTER TABLE
    CIUDAD
ADD
    CONSTRAINT CIUDAD_PK PRIMARY KEY (id_ciudad);

CREATE TABLE COMUNA (
    id_comuna NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1101 INCREMENT BY 1) NOT NULL,
    nombre_comuna VARCHAR2 (50) NOT NULL,
    CIUDAD_id_ciudad VARCHAR2 (40) NOT NULL
);

ALTER TABLE
    COMUNA
ADD
    CONSTRAINT COMUNA_PK PRIMARY KEY (id_comuna);

CREATE TABLE DIAGNOSTICO (
    id_diagnostico NUMBER (3) NOT NULL,
    nombre VARCHAR2 (25) NOT NULL,
    RECETA_id_receta NUMBER (7) NOT NULL
);

CREATE UNIQUE INDEX DIAGNOSTICO__IDX ON DIAGNOSTICO (RECETA_id_receta ASC);

ALTER TABLE
    DIAGNOSTICO
ADD
    CONSTRAINT DIAGNOSTICO_PK PRIMARY KEY (id_diagnostico);

CREATE TABLE DIGITADOR (
    id_digitador NUMBER (20) NOT NULL,
    pnombre VARCHAR2 (25) NOT NULL,
    papellido VARCHAR2 (25) NOT NULL
);

ALTER TABLE
    DIGITADOR
ADD
    CONSTRAINT DIGITADOR_PK PRIMARY KEY (id_digitador);

CREATE TABLE DOSIS (
    MEDICAMENTO_id_medicamento NUMBER (7) NOT NULL,
    id_receta NUMBER (7) NOT NULL,
    descripcion_dosis VARCHAR2 (100) NOT NULL
);

ALTER TABLE
    DOSIS
ADD
    CONSTRAINT DOSIS_PK PRIMARY KEY (id_receta);

CREATE TABLE ESPECIALIDAD (
    id_especialidad NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    especialidad VARCHAR2 (30) NOT NULL
);

ALTER TABLE
    ESPECIALIDAD
ADD
    CONSTRAINT ESPECIALIDAD_PK PRIMARY KEY (id_especialidad);

CREATE TABLE MEDICAMENTO (
    id_medicamento NUMBER (7) NOT NULL,
    nombre VARCHAR2 (25) NOT NULL,
    precio NUMBER NOT NULL,
    tipo_medicamento NUMBER (3) NOT NULL,
    via_administra NUMBER (3) NOT NULL,
    stock INTEGER NOT NULL,
    TIPO_MEDICAMENTO_id_tipo NUMBER NOT NULL
);

ALTER TABLE
    MEDICAMENTO
ADD
    CONSTRAINT MEDICAMENTO_PK PRIMARY KEY (id_medicamento);

CREATE TABLE MEDICO (
    rut_med NUMBER (8) NOT NULL,
    dv_med CHAR (1) NOT NULL,
    pnombre VARCHAR2 (25) NOT NULL,
    snombre VARCHAR2 (25),
    papellido VARCHAR2 (25) NOT NULL,
    sapellido VARCHAR2 (25),
    ESPECIALIDAD_id_especialidad NUMBER NOT NULL,
    telefono NUMBER NOT NULL UNIQUE
);

ALTER TABLE
    MEDICO
ADD
    CONSTRAINT CK_DV_MED CHECK (
        dv_med IN (
            '"1"',
            '"2"',
            '"3"',
            '"4"',
            '"5"',
            '"6"',
            '"7"',
            '"8"',
            '"9"',
            '"K"'
        )
    );

ALTER TABLE
    MEDICO
ADD
    CONSTRAINT MEDICO_PK PRIMARY KEY (rut_med);

CREATE TABLE PACIENTE (
    rut_pac VARCHAR2 (25) NOT NULL,
    dv_pac CHAR (1) NOT NULL,
    pnombre VARCHAR2 (25) NOT NULL,
    snombre VARCHAR2 (25),
    fecha_nacimiento DATE NOT NULL,
    telefono NUMBER (11) NOT NULL,
    COMUNA_id_comuna VARCHAR2 (15) NOT NULL
);

ALTER TABLE
    PACIENTE
ADD
    CONSTRAINT CK_DV_PAC CHECK (
        dv_pac IN (
            '"0"',
            '"1"',
            '"2"',
            '"3"',
            '"4"',
            '"5"',
            '"6"',
            '"7"',
            '"8"',
            '"9"',
            '"K"'
        )
    );

ALTER TABLE
    PACIENTE
ADD
    CONSTRAINT PACIENTE_PK PRIMARY KEY (rut_pac);

CREATE TABLE PAGO (
    id_boleta NUMBER (6) NOT NULL,
    id_receta_1 NUMBER (7) NOT NULL,
    fecha_pago DATE NOT NULL,
    monto_total NUMBER (10, 2) NOT NULL,
    metodo_pago VARCHAR2 (25) NOT NULL,
    BANCO_id_banco NUMBER (4) NOT NULL,
    RECETA_id_receta NUMBER (7) NOT NULL
);

ALTER TABLE
    PAGO
ADD
    CONSTRAINT PAGO_PK PRIMARY KEY (id_boleta);

CREATE TABLE RECETA (
    id_receta NUMBER (7) NOT NULL,
    observaciones VARCHAR2 (500),
    fecha_emision DATE NOT NULL,
    fecha_vencimiento DATE,
    duracion_tratamiento DATE,
    DIGITADOR_id_digitador NUMBER (20) NOT NULL,
    TIPO_RECETA_id_tipo_receta NUMBER NOT NULL,
    PACIENTE_rut_pac VARCHAR2 (25) NOT NULL,
    DIAGNOSTICO_id_diagnostico NUMBER (3) NOT NULL,
    MEDICO_rut_med NUMBER (8) NOT NULL,
    MEDICAMENTO_id_medicamento NUMBER (7) NOT NULL
);

CREATE UNIQUE INDEX RECETA__IDX ON RECETA (DIAGNOSTICO_id_diagnostico ASC);

ALTER TABLE
    RECETA
ADD
    CONSTRAINT RECETA_PK PRIMARY KEY (id_receta);

CREATE TABLE REGION (
    id_region VARCHAR2 (40) NOT NULL,
    nombre_region VARCHAR2 (50) NOT NULL
);

ALTER TABLE
    REGION
ADD
    CONSTRAINT REGION_PK PRIMARY KEY (id_region);

CREATE TABLE TIPO_MEDICAMENTO (
    id_tipo_med NUMBER NOT NULL,
    tipo_medicamento VARCHAR2 (30) NOT NULL
);

ALTER TABLE
    TIPO_MEDICAMENTO
ADD
    CONSTRAINT TIPO_MEDICAMENTO_PK PRIMARY KEY (id_tipo_med);

CREATE TABLE TIPO_RECETA (
    id_tipo_receta NUMBER NOT NULL,
    tipo_receta VARCHAR2 (20) NOT NULL
);

ALTER TABLE
    TIPO_RECETA
ADD
    CONSTRAINT TIPO_RECETA_PK PRIMARY KEY (id_tipo_receta);

ALTER TABLE
    CIUDAD
ADD
    CONSTRAINT CIUDAD_REGION_FK FOREIGN KEY (REGION_id_region) REFERENCES REGION (id_region);

ALTER TABLE
    COMUNA
ADD
    CONSTRAINT COMUNA_CIUDAD_FK FOREIGN KEY (CIUDAD_id_ciudad) REFERENCES CIUDAD (id_ciudad);

ALTER TABLE
    DIAGNOSTICO
ADD
    CONSTRAINT DIAGNOSTICO_RECETA_FK FOREIGN KEY (RECETA_id_receta) REFERENCES RECETA (id_receta);

ALTER TABLE
    DOSIS
ADD
    CONSTRAINT DOSIS_MEDICAMENTO_FK FOREIGN KEY (MEDICAMENTO_id_medicamento) REFERENCES MEDICAMENTO (id_medicamento);

ALTER TABLE
    MEDICAMENTO
ADD
    CONSTRAINT MEDICAMENTO_TIPO_FK FOREIGN KEY (TIPO_MEDICAMENTO_id_tipo) REFERENCES TIPO_MEDICAMENTO (id_tipo_med);

ALTER TABLE
    MEDICO
ADD
    CONSTRAINT MEDICO_ESPECIALIDAD_FK FOREIGN KEY (ESPECIALIDAD_id_especialidad) REFERENCES ESPECIALIDAD (id_especialidad);

ALTER TABLE
    PACIENTE
ADD
    CONSTRAINT PACIENTE_COMUNA_FK FOREIGN KEY (COMUNA_id_comuna) REFERENCES COMUNA (id_comuna);

ALTER TABLE
    PAGO
ADD
    CONSTRAINT PAGO_BANCO_FK FOREIGN KEY (BANCO_id_banco) REFERENCES BANCO (id_banco);

ALTER TABLE
    PAGO
ADD
    CONSTRAINT PAGO_RECETA_FK FOREIGN KEY (RECETA_id_receta) REFERENCES RECETA (id_receta);

ALTER TABLE
    RECETA
ADD
    CONSTRAINT RECETA_DIAGNOSTICO_FK FOREIGN KEY (DIAGNOSTICO_id_diagnostico) REFERENCES DIAGNOSTICO (id_diagnostico);

ALTER TABLE
    RECETA
ADD
    CONSTRAINT RECETA_DIGITADOR_FK FOREIGN KEY (DIGITADOR_id_digitador) REFERENCES DIGITADOR (id_digitador);

ALTER TABLE
    RECETA
ADD
    CONSTRAINT RECETA_MEDICAMENTO_FK FOREIGN KEY (MEDICAMENTO_id_medicamento) REFERENCES MEDICAMENTO (id_medicamento);

ALTER TABLE
    RECETA
ADD
    CONSTRAINT RECETA_MEDICO_FK FOREIGN KEY (MEDICO_rut_med) REFERENCES MEDICO (rut_med);

ALTER TABLE
    RECETA
ADD
    CONSTRAINT RECETA_PACIENTE_FK FOREIGN KEY (PACIENTE_rut_pac) REFERENCES PACIENTE (rut_pac);

ALTER TABLE
    RECETA
ADD
    CONSTRAINT RECETA_TIPO_RECETA_FK FOREIGN KEY (TIPO_RECETA_id_tipo_receta) REFERENCES TIPO_RECETA (id_tipo_receta);

ALTER TABLE
    PAGO
ADD
    CONSTRAINT CK_METODO_PAGO CHECK (
        metodo_pago IN ('EFECTIVO', 'TARJETA', 'TRANSFERENCIA')
    );

ALTER TABLE
    MEDICAMENTO
ADD
    CONSTRAINT CK_MEDICAMENTO_PRECIO CHECK (
        precio BETWEEN 1000
        AND 2000000
    );